In [18]:
import re
result = re.search(r"^(\w*), (\w*)$", "L2_velace, Ada")
print(result)
print(result.groups())
print(result[1])
print(result[2])
print(result[0])
"{} {}".format(result[2],result[1],result[0])
def rearrange_name(name):
    result = re.search(r"^([\w\.-]*), ([\w\.-]*)$", name)
    if result is None:
        return name
    return "{} {}".format(result[2], result[1])

rearrange_name("Ritchie, Valens P.")

<re.Match object; span=(0, 14), match='L2_velace, Ada'>
('L2_velace', 'Ada')
L2_velace
Ada
L2_velace, Ada


'Ritchie, Valens P.'

In [19]:
import re
re.split(r"[.?!]", "One sentence. Another one? And the last one!")

['One sentence', ' Another one', ' And the last one', '']

In [20]:
re.split(r"([.?!])", "One sentence. Another one? And the last one!")

['One sentence', '.', ' Another one', '?', ' And the last one', '!', '']

In [21]:
re.sub(r"[\w.%+-]+@[\w.-]+", "[REDACTED]", "Receieved an email for go_nuts95@my.example.com")

'Receieved an email for [REDACTED]'

In [25]:
re.sub(r"^([\w.-]*), ([\w .-]*)$", r"\2 \1", "Lovelace, Ada")

'Ada Lovelace'

In [26]:
import re
def transform_comments(line_of_code):
  result = re.sub(r'##*',r'//', line_of_code)
  return result

print(transform_comments("### Start of program")) 
# Should be "// Start of program"
print(transform_comments("  number = 0   ## Initialize the variable")) 
# Should be "  number = 0   // Initialize the variable"
print(transform_comments("  number += 1   # Increment the variable")) 
# Should be "  number += 1   // Increment the variable"
print(transform_comments("  return(number)")) 
# Should be "  return(number)"

// Start of program
  number = 0   // Initialize the variable
  number += 1   // Increment the variable
  return(number)


In [27]:
import re
def convert_phone_number(phone):
  result = re.sub(r" (\d{3})-",r" (\1) ",phone)
  return result    

print(convert_phone_number("My number is 212-345-9999.")) # My number is (212) 345-9999.
print(convert_phone_number("Please call 888-555-1234")) # Please call (888) 555-1234
print(convert_phone_number("123-123-12345")) # 123-123-12345
print(convert_phone_number("Phone number of Buckingham Palace is +44 303 123 7300")) # Phone number of Buckingham Palace is +44 303 123 7300

My number is (212) 345-9999.
Please call (888) 555-1234
123-123-12345
Phone number of Buckingham Palace is +44 303 123 7300


In [28]:
import re
def multi_vowel_words(text):
  pattern = r"\b\w*[aeiou]{3,}\w*\b"
  result = re.findall(pattern, text)
  return result

print(multi_vowel_words("Life is beautiful")) 
# ['beautiful']

print(multi_vowel_words("Obviously, the queen is courageous and gracious.")) 
# ['Obviously', 'queen', 'courageous', 'gracious']

print(multi_vowel_words("The rambunctious children had to sit quietly and await their delicious dinner.")) 
# ['rambunctious', 'quietly', 'delicious']

print(multi_vowel_words("The order of a data queue is First In First Out (FIFO)")) 
# ['queue']

print(multi_vowel_words("Hello world!")) 
# []

['beautiful']
['Obviously', 'queen', 'courageous', 'gracious']
['rambunctious', 'quietly', 'delicious']
['queue']
[]


In [ ]:
#!/usr/bin/env python3
import re
import csv
def contains_domain(address, domain):
  """Returns True if the email address contains the given,domain,in the domain position, false if not."""
  domain = r'[\w\.-]+@'+domain+'$'
  if re.match(domain,address):
    return True
  return False
def replace_domain(address, old_domain, new_domain):
  """Replaces the old domain with the new domain in the received address."""
  old_domain_pattern = r'' + old_domain + '$'
  address = re.sub(old_domain_pattern, new_domain, address)
  return address
def main():
  """Processes the list of emails, replacing any instances of the old domain with the new domain."""
  old_domain, new_domain = 'abc.edu', 'xyz.edu'
  csv_file_location = '<csv_file_location>'
  report_file = '<path_to_home_directory>' + '/updated_user_emails.csv'
  user_email_list = []
  old_domain_email_list = []
  new_domain_email_list = []
  with open(csv_file_location, 'r') as f:
    user_data_list = list(csv.reader(f))
    user_email_list = [data[1].strip() for data in user_data_list[1:]]
    for email_address in user_email_list:
      if contains_domain(email_address, old_domain):
        old_domain_email_list.append(email_address)
        replaced_email = replace_domain(email_address,old_domain,new_domain)
        new_domain_email_list.append(replaced_email)
    email_key = ' ' + 'Email Address'
    email_index = user_data_list[0].index(email_key)
    for user in user_data_list[1:]:
      for old_domain, new_domain in zip(old_domain_email_list, new_domain_email_list):
        if user[email_index] == ' ' + old_domain:
          user[email_index] = ' ' + new_domain
  f.close()
  with open(report_file, 'w+') as output_file:
    writer = csv.writer(output_file)
    writer.writerows(user_data_list)
    output_file.close()
main()

In [3]:
usernames = {}
name = "good_user"
usernames[name] = usernames.get(name, 0) +1
print(usernames)


{'good_user': 1}


: 

In [ ]:
def find_item(list, item):
  #Returns True if the item is in the list, False if not.
  if len(list) == 0:
    return False

  #Is the item in the center of the list?
  middle = len(list)//2
  if list[middle] == item:
    return True

  #Is the item in the first half of the list? 
  if item < list[middle]:
    #Call the function with the first half of the list
    return find_item(list[middle], item)
  else:
    #Call the function with the second half of the list
    return find_item(list[middle+1:], item)

  return False

#Do not edit below this line - This code helps check your work!
list_of_names = ["Parker", "Drew", "Cameron", "Logan", "Alex", "Chris", "Terry", "Jamie", "Jordan", "Taylor"]

print(find_item(list_of_names, "Alex")) # True

: 

: 

In [4]:
#! /usr/bin/python

import matplotlib.pyplot as plt
import numpy as np

a=[[11,12,13],[21,22,23],[31,32,33]]
a

A=np.array(a)
A
A.ndim
A.shape

(3, 3)

In [5]:
A.shape

(3, 3)

In [6]:
A.ndim

2

In [5]:
A.size

9

In [7]:
A[1,2]

23

In [8]:
A[1][2]

23

In [8]:
A[0][0]

11

In [9]:
A[0][0:2]

array([11, 12])

In [9]:
a=[[11,12,13],[21,22,23],[31,32,33]]
a

A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [12]:
x=np.array([[1,0],[0,1]])
x

array([[1, 0],
       [0, 1]])

In [10]:
y=np.array([[2,1],[1,2]])
y

array([[2, 1],
       [1, 2]])

In [13]:
z=x+y
z

array([[3, 1],
       [1, 3]])

In [14]:
z=2*y
z

array([[4, 2],
       [2, 4]])

In [17]:
a=np.array([[-1,1],[2,-1][3,2]])
b=np.array([[1,0,2],[0,1,2]])
z=np.dot(a,b)
z


TypeError: list indices must be integers or slices, not tuple

In [19]:
a=np.array([[-1,1],[2,-1][3,2]])
b=np.array([[1,0,2],[0,1,2]])
c=np.dot(a,b) 

TypeError: list indices must be integers or slices, not tuple

In [2]:
a=np.array([[0,1,1],[1,0,1]])
b=np.array([[1,1],[1,1],[-1,1]])
z=np.dot(a,b)
z

NameError: name 'np' is not defined

In [24]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [26]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

In [ ]:
1*0+2*2
0*1+2*2 

In [27]:
df=pd.DataFram(dict_)
type(df)

NameError: name 'pd' is not defined

In [1]:
pip install requests

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install BeautifulSoup

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Josh\AppData\Local\Temp\pip-install-smzelegt\beautifulsoup_870ddc3ffdf54e88980a72fbe11e970a\setup.py", line 3
          "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."
                                                                                                          ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an is

In [3]:
pip install BeautifulSoup4

Note: you may need to restart the kernel to use updated packages.


In [4]:
%%html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>
<h3><b id='boldest'>Lebron James</b></h3>
<p> Salary: $ 92,000,000 </p>
<h3> Stephen Curry</h3>
<p> Salary: $85,000, 000 </p>
<h3> Kevin Durant </h3>
<p> Salary: $73,200, 000</p>
</body>
</html>

In [5]:
html="<!DOCTYPE html><html><head><title>Page Title</title></head><body><h3><b id='boldest'>Lebron James</b></h3><p> Salary: $ 92,000,000 </p><h3> Stephen Curry</h3><p> Salary: $85,000, 000 </p><h3> Kevin Durant </h3><p> Salary: $73,200, 000</p></body></html>"

In [8]:
soup = BeautifulSoup(html, "html.parser")

NameError: name 'BeautifulSoup' is not defined

In [9]:
print(soup.prettify())

NameError: name 'soup' is not defined

In [10]:
tag_object=soup.title
print("tag object:",tag_object)

NameError: name 'soup' is not defined

In [11]:
%%html
<table>
  <tr>
    <td id='flight' >Flight No</td>
    <td>Launch site</td> 
    <td>Payload mass</td>
   </tr>
  <tr> 
    <td>1</td>
    <td><a href='https://en.wikipedia.org/wiki/Florida'>Florida</a></td>
    <td>300 kg</td>
  </tr>
  <tr>
    <td>2</td>
    <td><a href='https://en.wikipedia.org/wiki/Texas'>Texas</a></td>
    <td>94 kg</td>
  </tr>
  <tr>
    <td>3</td>
    <td><a href='https://en.wikipedia.org/wiki/Florida'>Florida<a> </td>
    <td>80 kg</td>
  </tr>
</table>

In [12]:
var = '01234567'
print(var[::2])

0246


In [17]:
Name="EmiLy"
Name[3]


'L'

In [18]:
float(3)

3.0

In [19]:
1/2

0.5

In [20]:
x=2/2
type(x)

float

In [21]:
A=('a','b','c')
A[:]

('a', 'b', 'c')

In [22]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [23]:
def add(x): return(x+x) add('1')

SyntaxError: invalid syntax (2121502255.py, line 1)

In [24]:
def add(x): return(x+x+x) add('1') 

SyntaxError: invalid syntax (1235050410.py, line 1)

In [26]:
def add(x): 
    return(x+x) 

add(1) 

2

In [29]:
A=[8,5,2] 
for a in A: 
    print(12-a) 

4
7
10


In [30]:
for i in range(1,5): 
    if (i!=2): 
        print(i) 

1
3
4


In [33]:
class Rectangle(object):
        def __init__(self,width=2,height =3,color='r'):
                                  self.height=height
                                  self.width=width
                                  self.color=color
def drawRectangle(self):
                    import matplotlib.pyplot as plt
                    plt.gca().add_patch(plt.Rectangle((0, 0),self.width, self.height ,fc=self.color))
                    plt.axis('scaled')
                    plt.show()

In [36]:
import numpy
a=np.array([0,1,0,1,0]) 
b=np.array([1,0,1,0,1]) 
a*b

NameError: name 'np' is not defined